import { Company } from "@/types/companies";

export const mockCompanies: Company[] = [
  {
    status: "Na stronie", 
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Na stronie",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Usunięto",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Na stronie",     
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Usunięto",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Usunięto",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Usunięto",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Usunięto",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Usunięto", 
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Na stronie",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Na stronie", 
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Na stronie", 
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Na stronie",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Na stronie",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
  {
    status: "Na stronie",
    name: "Valeo",
    logo_url: "/logo/example_logo.png",
    website_url: "https://www.valeo.com/pl/polska/",
    opinion: "Super organizaja, najlepsi studenci",
    rating: 5,
  },
];